version: '3.8'
services:
  dev-db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=godcode
      - POSTGRES_PASSWORD=mypass123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  postgres: