version: '3.8'
services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '9000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    depends_on:
      - dev-db
    command: bash -c "npm run start"

  dev-db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=godcode
      - POSTGRES_PASSWORD=mypass123
      - POSTGRES_DB=database_mis
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  postgres:
