services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    command: sh -c "npx prisma generate && npm run start"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: godcode
      POSTGRES_PASSWORD: godcode
      POSTGRES_DB: db_mispens
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres:
